expect_equal(reOnly(~ 1 + x + y + (1|f) + (1|g)), ~(us(1 | f)) + (us(1 | g)))
expect_equal(addForm0(y~x,~1), y ~ x+1)
expect_equal(addForm0(~x,~y), ~x+y)
ff <- findbars_x(y~1+(x|f/g))
## deparse in tests to avoid having to deal with raw expressions/language objects
expect_equal(deparse(expandAllGrpVar(ff)), "list(us(x | g:f), us(x | f))")
expect_equal(deparse(expandAllGrpVar(quote(1|(f/g)/h))), "list(1 | h:g:f, 1 | g:f, 1 | f)")
expect_equal(deparse(expandAllGrpVar(quote(1|f/g/h))),  "list(1 | h:g:f, 1 | g:f, 1 | f)")
expect_equal(deparse(expandAllGrpVar(quote(1|f*g))), "list(1 | f, 1 | g, 1 | f:g)")
expect_equal(deparse(expandAllGrpVar(quote(1|f+g))), "list(1 | f, 1 | g)")
expect_equal(deparse(expandAllGrpVar(quote(a+b|f+g+h*i))), "list(a + b | f, a + b | g, a + b | h, a + b | i, a + b | h:i)")
expect_equal(deparse(expandAllGrpVar(quote(s(log(d), k = 4)))), "list(s(log(d), k = 4))")
expect_equal(deparse(expandAllGrpVar(quote(s(log(d+1))))), "list(s(log(d + 1)))")
expect_equal(deparse1(splitForm(quote(us(x,n=2)))),
             "list(fixedFormula = ~1, reTrmFormulas = list(x), reTrmAddArgs = list(us(n = 2)), reTrmClasses = \"us\")")
expect_equal(deparse(expandAllGrpVar(quote((1 | a / (b*c))))), "list((1 | c:b:a), (1 | c:a), (1 | b:a), (1 | a))")
expect_equal(deparse(expandAllGrpVar(quote((1 | a / (b+c))))), "list((1 | c:a), (1 | b:a), (1 | a))")

if (FALSE) {
    ## FIXME: keep chipping away at this
expect_equal(findbars_x(~ 1 + (x + y || g), expand_doublevert_method = "diag_special"))
expect_equal(findbars_x(~ 1 + (x + y || g), expand_doublevert_method = "split"))
expect_equal(findbars_x(~ 1 + (1 | f) + (1 | g)))
expect_equal(findbars_x(~ 1 + (1 | f) + (1 | g)))
expect_equal(findbars_x(~ 1 + (1|h) + (x + y || g), expand_doublevert_method = "split"))
expect_equal(findbars_x(~ 1 + (1|Subject)))
expect_equal(findbars_x(~ (1||Subject)))
expect_equal(findbars_x(~ (1|Subject)))
expect_equal(findbars_x(~ (1|Subject), default.special = NULL))
expect_equal(findbars_x(~ 1 + x))
expect_equal(findbars_x(~ s(x, bs = "tp")))
expect_equal(findbars_x(y ~ a + log(b) + s(x, bs = "tp") + s(y, bs = "gp")), target = "s", default.special = NULL)
expect_equal(inForm(z~.,quote(.)))
expect_equal(inForm(z~y,quote(.)))
expect_equal(inForm(z~a+b+c,quote(c)))
expect_equal(inForm(z~a+b+(d+e),quote(c)))
f <- ~ a + offset(x)
f2 <- z ~ a
expect_equal(inForm(f,quote(offset)))
expect_equal(inForm(f2,quote(offset)))
expect_equal(extractForm(~a+offset(b),quote(offset)))
expect_equal(extractForm(~c,quote(offset)))
expect_equal(extractForm(~a+offset(b)+offset(c),quote(offset)))
expect_equal(extractForm(~offset(x),quote(offset)))
expect_equal(dropHead(~a+offset(b),quote(offset)))
expect_equal(dropHead(~a+poly(x+z,3)+offset(b),quote(offset)))
expect_equal(drop.special(x~a + b+ offset(z)))
expect_equal(replaceForm(quote(a(b+x*c(y,z))),quote(y),quote(R)))
expect_equal(ss <- ~(1 | cask:batch) + (1 | batch))
expect_equal(replaceForm(ss,quote(cask:batch),quote(batch:cask)))
expect_equal(replaceForm(ss, quote(`:`), quote(`%:%`)))
}
